// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb_register

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegisterClient is the client API for Register service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterClient interface {
	// Client asks to RegisterServer where is a StorageServer close to him
	GetCloseStorageServers(ctx context.Context, in *ClientMsg, opts ...grpc.CallOption) (*ListOfStorageServerMsg, error)
	// StorageServer asks RegisterServer for others StorageServers
	GetListOfPeers(ctx context.Context, in *StorageServerMsg, opts ...grpc.CallOption) (*ListOfStorageServerMsg, error)
	// StorageServer comunicate that is still alive
	Heartbeat(ctx context.Context, in *StorageServerMsg, opts ...grpc.CallOption) (*ListOfStorageServerMsg, error)
}

type registerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterClient(cc grpc.ClientConnInterface) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) GetCloseStorageServers(ctx context.Context, in *ClientMsg, opts ...grpc.CallOption) (*ListOfStorageServerMsg, error) {
	out := new(ListOfStorageServerMsg)
	err := c.cc.Invoke(ctx, "/register.Register/GetCloseStorageServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerClient) GetListOfPeers(ctx context.Context, in *StorageServerMsg, opts ...grpc.CallOption) (*ListOfStorageServerMsg, error) {
	out := new(ListOfStorageServerMsg)
	err := c.cc.Invoke(ctx, "/register.Register/GetListOfPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerClient) Heartbeat(ctx context.Context, in *StorageServerMsg, opts ...grpc.CallOption) (*ListOfStorageServerMsg, error) {
	out := new(ListOfStorageServerMsg)
	err := c.cc.Invoke(ctx, "/register.Register/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServer is the server API for Register service.
// All implementations must embed UnimplementedRegisterServer
// for forward compatibility
type RegisterServer interface {
	// Client asks to RegisterServer where is a StorageServer close to him
	GetCloseStorageServers(context.Context, *ClientMsg) (*ListOfStorageServerMsg, error)
	// StorageServer asks RegisterServer for others StorageServers
	GetListOfPeers(context.Context, *StorageServerMsg) (*ListOfStorageServerMsg, error)
	// StorageServer comunicate that is still alive
	Heartbeat(context.Context, *StorageServerMsg) (*ListOfStorageServerMsg, error)
	mustEmbedUnimplementedRegisterServer()
}

// UnimplementedRegisterServer must be embedded to have forward compatible implementations.
type UnimplementedRegisterServer struct {
}

func (UnimplementedRegisterServer) GetCloseStorageServers(context.Context, *ClientMsg) (*ListOfStorageServerMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCloseStorageServers not implemented")
}
func (UnimplementedRegisterServer) GetListOfPeers(context.Context, *StorageServerMsg) (*ListOfStorageServerMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListOfPeers not implemented")
}
func (UnimplementedRegisterServer) Heartbeat(context.Context, *StorageServerMsg) (*ListOfStorageServerMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedRegisterServer) mustEmbedUnimplementedRegisterServer() {}

// UnsafeRegisterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterServer will
// result in compilation errors.
type UnsafeRegisterServer interface {
	mustEmbedUnimplementedRegisterServer()
}

func RegisterRegisterServer(s grpc.ServiceRegistrar, srv RegisterServer) {
	s.RegisterService(&Register_ServiceDesc, srv)
}

func _Register_GetCloseStorageServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).GetCloseStorageServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register.Register/GetCloseStorageServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).GetCloseStorageServers(ctx, req.(*ClientMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Register_GetListOfPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageServerMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).GetListOfPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register.Register/GetListOfPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).GetListOfPeers(ctx, req.(*StorageServerMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Register_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageServerMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register.Register/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Heartbeat(ctx, req.(*StorageServerMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Register_ServiceDesc is the grpc.ServiceDesc for Register service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Register_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "register.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCloseStorageServers",
			Handler:    _Register_GetCloseStorageServers_Handler,
		},
		{
			MethodName: "GetListOfPeers",
			Handler:    _Register_GetListOfPeers_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Register_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_register/Register.proto",
}
